name: first workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello github"
      - name: print goodbye
        run: echo "bye chads"
        
